dataset_config:
  dataset_split:
    train: [
      "RAK_S8-18b_THIN-REFL5_L0_P1-4_3400_2048_2048",
      "RAK_S8-18b_THIN-NANOL4_L3_P1-4_3400_2048_2048",
      "RAK_S8-18b_INTMED-REFR6_L3_P1-4_3450_2048_2048",
      "RAK_S8-18b_INTMED-NANOL4_L3_P1-4_3400_2048_2048",
      "RAK_S8-18b_THICK-REFL5_L1_P1-4_3400_2048_2048",
      "RAK_S8-18b_THICK-REFL5_L3_P1-4_3450_2048_2048",
      "RAK_S8-18b_THICK-NANOL2_L1_P1-4_3400_2048_2048",
      "RAK_S8-18b_THICK-NANOL2_L3_P1-4_3400_2048_2048"
    ]
    validation: [
      "RAK_S8-18b_THIN-REFL5_L3_P1-4_3400_2048_2048",
      "RAK_S8-18b_THICK-REFL5_L0_P1-4_3400_2048_2048",
      "RAK_S8-18b_THICK-NANOL2_L0_P1-4_3400_2048_2048"
    ]
#    test: [
#      "",
#    ]
  stack_downsampling:
    type: 'linear' # 'None', 'random', 'linear', 'from_start', 'from_end'
#    frac: 1.0  # if 'random', 'linear', 'from_start', or 'from_end' selected; ignored if `None` selected
    number_of_images: 410  # if 'random', 'linear', 'from_start', or 'from_end' selected; ignored if `None` selected
    num_skip_beg_slices: 0 # trims n slices off of beginning of stack with N total slices. Slice n+1 becomes new Slice 1
    num_skip_end_slices: 2 # trims m slices off of end of stack with N total slices. Slice N-(m+1) becomes new last slice
  target_size: [512, 512]  # width, height
  image_cropping:
    type: 'random' # 'None' (downscale to target), 'linear' (def # crops), 'random' (def # crops), 'class' (def # crops), 'all' (all crops)
    num_per_image: 10 # if type 'linear' (translation) or 'random' selected, then is num of crops (of target size) per image
    num_pos_per_class: 2 # if type 'class', then is num of random class-positive crops (of target sz) per img, >0
    num_neg_per_class: 2 # if type 'class', then is num of random class-negative crops (of target sz) per img, >=0
    min_num_class_pos_px: # if type 'class', then is min num of class-pos pixels required in given class-pos crop, >0
      class_0_pos_px: 5 # 'delam_damage', '0-degree_damage', '90-degree_damage'
#      class_0_pos_px: 5 # '0-degree_damage'
#      class_1_pos_px: 5 # '45-degree_damage'
#      class_2_pos_px: 5  # '90-degree_damage'
  class_annotation_mapping:
    class_0_annotation_GVs: [50, 100, 250]
#    class_0_annotation_GVs: [50]  # 'delam_damage'
#    class_1_annotation_GVs: [100]  # '0-degree_damage'
#    class_2_annotation_GVs: [250]  # '90-degree_damage'
